disabled_rules: # rule identifiers turned on by default to exclude from running
  - line_length
  - force_cast
  - trailing_whitespace
  - todo
  - file_length
  - unused_setter_value
  - type_body_length
  - identifier_name
